#if 1

#include <iostream>

class MyClass {
public:
    // Default constructor (generated by the compiler)
    MyClass() = default;
    MyClass(int i)  {}

    // Copy constructor (generated by the compiler)
    MyClass(const MyClass&) = delete;

    // Destructor (generated by the compiler)
    ~MyClass() = default;
   
    // Deleted copy assignment operator
    MyClass& operator=(const MyClass&) = delete;
};

int main() {
    MyClass obj; // Calls the default constructor
    return 0;
}


#endif